Develop
AlexsandrBrachii/java-filmorate pull request #22
Opened 2023-05-03 17:32 UTC by AlexsandrBrachii

2023-05-04 12:37 UTC, TomattmanYandex requested changes
Комментов много комменты в кода
Проверял поп порядку заданий, поэтому могут быть в очень непонятном порядке
добавлю основные еще раз тут
1) вы работаете как команда надо одним проектом, и надо чтобы проект выглядел так как будто над ним работает команда а не  несколько отдельных человек (т.е. примерно один стиль выоплнения, стиль именования переменных, стиль выполнения классов)
2) не допускаются запросы с двумя вложенными подзапросами
3) количество запросов в базу должно быть константным , т.е. не зависеть например от количества фильмов
4) нужно обновить схему базы, и дописать кто над чем работал и состав команды
Может что то забыл, но чуть что все коменты в коде

2023-05-04 12:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public List<Film> getRecommendations(List<Integer> recommendedFilmsIds) {
как можно улучшить этот метод
1) переименовать, так как по сути к рекомендациям он имеет только косвенное отношение
мы тут просто ищем фильм по набору id 
2) снова повторюсь про проблему количества запросов
3) улучшение другого метода, но добавлю его тут поиск фильма по id это по сити поиск фильма по списку id только где в списке только один элемент -> следовательно можно переделать метод getById

2023-05-04 12:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    int eventId;
и числовые значения лучше сделать классами обертками

2023-05-04 12:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/h2/mapper/EventMapper.java
> +public class EventMapper implements RowMapper<Event> {
почему для каких то объектов маппер в отдельном классе для каких то нет?
следует сделать в одном стиле

2023-05-04 12:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +            String sqlQuery = "DELETE  FROM FRIENDS WHERE USER_ID =? OR FRIEND_ID =?;" +
лучше сделать это как три разных запроса ибо текущий вариант слабо читаем

2023-05-04 12:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            String sqlQuery = "DELETE FROM LIKES WHERE FILM_ID =?;" +
лучше сделать 3 разных запроса, будет лучше читаемым
а еще какжется тут не хватает режисеров

2023-05-04 12:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return filmStorageDb.findByDirectorIdAndSortByRelateDate(directorId)
содержимое блока отличается только одним методом
дубликация кода не лучшеая практика, почему бы результат этого вызова не записать в переменную , (так же через if) а уже все одинаковые действия выполнять с значением этой переменной

2023-05-04 12:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        String message = String.format("Сортировка по типу %s отсутствует", sortBy);
это логика сервиса

2023-05-04 12:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/h2/DirectorH2Impl.java
> +public class DirectorH2Impl implements DirectorRepository {
все классы хранилища в одном пакете, этот в другом, все с одним алгоритмом именования этот в другом, надо сделать все однотипно

2023-05-04 13:17 UTC, Tor1ant commented on README.md
>  ![database filmorate](https://github.com/AlexsandrBrachii/java-filmorate/blob/add-database/database_filmorate.png)
картинка будет подгружена.

2023-05-04 13:41 UTC, Tor1ant commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<Film> getRecommendations(int id) {
в работе.

2023-05-04 15:19 UTC, Tor1ant commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +            String sqlQuery = "DELETE  FROM FRIENDS WHERE USER_ID =? OR FRIEND_ID =?;" +
в работе

2023-05-04 15:23 UTC, Tor1ant commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            String sqlQuery = "DELETE FROM LIKES WHERE FILM_ID =?;" +
в работе

2023-05-04 20:47 UTC, DyadAnYa10 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        String message = String.format("Сортировка по типу %s отсутствует", sortBy);
Подскажите, в чем замечание? Мы же и находимся в сервисе.

2023-05-04 22:43 UTC, DyadAnYa10 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return filmStorageDb.findByDirectorIdAndSortByRelateDate(directorId)
+

2023-05-07 19:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/impl/ReviewStorageImpl.java
> +            ps.setInt(3, review.getUseful() == null ? 0 : calculateReviewUseful(keyHolder.getKey().intValue()));
коммент оставлю в схеме, но тут придётся переделать

2023-05-07 19:20 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +  rating_useful INTEGER,
это поле высчитываемое,  высчитывается исходя из таблицы review_useful следовательно зачем хранить значение
когда мы храним высчитываемое значение может получиться ситуация, что храним мы одно значение но на самом деле оно другое

Стоит удалить это поле и в хранилище высчитывать полезность

2023-05-07 19:20 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +    rating ENUM('like', 'dislike'),
так как поле может иметь только два значение не лучше ли использовать boolean значение например isPositive  true будет аналогично лайку false дизлайку

2023-05-07 19:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/impl/ReviewStorageImpl.java
> +        updateUsefulForReview(review);
просто пометочка для себя, чтобы потом проверить

2023-05-07 19:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/impl/ReviewStorageImpl.java
> +    public void makeDislikeReview(int reviewId, int userId) {
этот метод и makeLikeReview отличаются минимально, лучше оставить один метод но с параметром
то же каксается и удаления лайков и дизлайков

2023-05-07 19:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .peek(this::collectDirectors)
а тут ничего не справлено

2023-05-07 19:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            .peek(this::collectDirectors)
N + 1 запрос

2023-05-07 19:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void filmDirectorExecuteProcessing(Film film, Film filmForResult) {
непонятный метод

2023-05-07 19:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .map(director -> directorRepository.findById(director.getId()))
снова N + 1 запрос

2023-05-07 19:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            .peek(this::collectDirectors)
N + 1 запрос

2023-05-07 19:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/impl/FilmStorageImpl.java
> +        return popularFilms.stream().limit(count).collect(Collectors.toList());
количество лучше вынести в запрос
что будет если в базе 100 фильмов, а если 1000 или 10000 в случае если проблемы с сетью такой запрос будет выполняться в разы дольше чем с ограничением количетсва (точнее не выполняться а передаваться данные по сети)

2023-05-07 19:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +            User user = User.builder().id(userLikesRs.getInt("user_id"))
хорошо, но зачем нужен email и name разве id будет недостаточно?

2023-05-07 19:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/h2/mapper/EventMapper.java
> +package ru.yandex.practicum.filmorate.dao.h2.mapper;
какое отношение маппер имеет к h2 базе? он будет универсален, а следовательно h2 в пакете явно лишнее

2023-05-07 19:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/h2/mapper/EventMapper.java
> +public class EventMapper implements RowMapper<Event> {
это еще актуально, хотя бы какую ни будь отписку оставьте)))

2023-05-07 19:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        String message = String.format("Сортировка по типу %s отсутствует", sortBy);
Ой, мой косяк, запутался в обилии классов

2023-05-07 19:35 UTC, TomattmanYandex requested changes
Есть еще много моментов которые надо поправить, по поводу количества запросов за режиссёрам,
рекомендую сделать метод который будет принимать список фильмов, собирать их id
делать запрос в базу на получение id  фильма, id режиссёра, Имя, c ограничением where film_id in (тут список id) собрать результат в map<Long,List<Director>> где long - id фильма а после чего пройтись по всем фильмам из списка и проставить им режиссеров из мапы

2023-05-07 19:35 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/event_enum/EventType.java
> +package ru.yandex.practicum.filmorate.dao.event_enum;
очень бросается в глаза именование пакета, может сделать просто enum  ну или хотя бы в camelCase

2023-05-07 21:15 UTC, Tor1ant commented on src/main/java/ru/yandex/practicum/filmorate/impl/FilmStorageImpl.java
> +        return popularFilms.stream().limit(count).collect(Collectors.toList());
Исправлено.

2023-05-09 23:15 UTC, TomattmanYandex requested changes
Проблема N+1 запроса не решена, без ее решения принять не смогу

2023-05-10 09:57 UTC, TomattmanYandex approved these changes
Принято

2023-05-15 08:06 UTC, merged